name: chatGPT review

permissions:
  contents: read
  pull-requests: write

on: pull_request

jobs:
  chatgpt-review:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: unsafecoerce/chatgpt-action@release/v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: true 
          action: review
          review_comment_lgtm: true
          review_beginning: |
            Hi ChatGPT, I have a pull request with title "$title" and the description is as follows,
      
            > $description.
      
            Next, I will given you a series of patches, each of them consists of a filename and a diff
            snippet, and you need to do a brief code review for every message, and tell me any bug risk
            and improvement suggestion and code refactoring suggestions code. If the patch is looks good and acceptable, please reply "LGTM!"
            with a short comment with 30 words.
      
            You answer should be in spanish language. Don't include the diff in your comment, and markdown format is
            preferred. Reply "OK" to confirm.
