name: test

permissions:
  contents: read
  pull-requests: write

on: pull_request

jobs:
  sun-ai-code-reviewer:
    environment: "test"
    runs-on: ubuntu-latest
    steps:
      - uses: unsafecoerce/chatgpt-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHATGPT_ACCESS_TOKEN: ${{ secrets.CHATGPT_ACCESS_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          action: review
          review_comment_lgtm: true
          path_filters:
            - "*"