name: Code Review

on: pull_request

jobs:
  test:
    # if: ${{ contains(github.event.*.labels.*.name, 'gpt review') }} # Optional; to run only when a label is attached
    runs-on: ubuntu-latest
    steps:
    - name: gpt-review
      uses: microsoft/gpt-review@v0.9.4
            