on: pull_request
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: ChatGPT explain code
    steps:
      - uses: actions/checkout@v4
      - name: Chat GPT Code Peer Review
        uses: edelauna/gpt-review@v1
        with:
          # OpenAI API key used for sending patch diffs for review.
          # Required
          openai_api_key: ${{ secrets.openai_api_key }}
      
          # The target branch for the git diff to run against.
          # Default: ${{ github.base_ref }}
          target_branch: ${{ github.base_ref }}